
# Generated by Django 5.2.10 on 2026-01-10 17:19


# GreenBite-backend/food/migrations/0001_initial.py <<<<origin/feature/marketplace/frontend
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSafetyScanJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('image_path', models.TextField(blank=True, default='')),
                ('image_key', models.TextField(blank=True, default='')),
                ('food_name', models.CharField(blank=True, default='', max_length=255)),
                ('storage', models.CharField(blank=True, default='', max_length=255)),
                ('opened_days', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_safety_scan_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.TextField()),
                ('ingredients', models.JSONField()),
                ('steps', models.JSONField(blank=True, default=list)),
                ('serving', models.IntegerField(blank=True, null=True)),
                ('waste', models.JSONField(blank=True, default=list)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('has_leftovers', models.BooleanField(default=False)),
                ('leftovers_saved', models.BooleanField(default=False)),
                ('leftovers', models.JSONField(blank=True, null=True)),
                ('cuisine', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('mealTime', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('brunch', 'Brunch'), ('dessert', 'Dessert'), ('appetizer', 'Appetizer')], max_length=20)),
                ('consumed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_mealdb_id', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
                'ordering': ['-consumed_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodLogSys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('bread', 'Bread'), ('meat', 'Meat'), ('dairy', 'Dairy'), ('grain', 'Grain'), ('other', 'Other')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('storage_type', models.CharField(choices=[('fridge', 'Fridge'), ('freezer', 'Freezer'), ('room_temp', 'Room Temperature')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_normalized', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('is_consumed', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to='food.meal')),
            ],
            options={
                'verbose_name': 'Food Log Entry',
                'verbose_name_plural': 'Food Log Entries',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('why', models.TextField()),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(max_length=20)),
                ('disposal', models.CharField(max_length=50)),
                ('reuse_ideas', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_logs', to='food.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waste Log',
                'verbose_name_plural': 'Waste Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodLogUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('foodlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.foodlogsys')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foodlog_usages', to='recipes.mealdbrecipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(blank=True, db_column='meal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foodlog_usages', to='food.meal')),
            ],
            options={
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['user', 'used_at'], name='food_foodlo_user_id_a6cd09_idx'), models.Index(fields=['recipe'], name='food_foodlo_recipe__078a6d_idx'), models.Index(fields=['foodlog'], name='food_foodlo_foodlog_d801a2_idx')],
            },
        ),
    ]
