# Generated by Django 5.2.9 on 2025-12-20 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLogSys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('bread', 'Bread'), ('meat', 'Meat'), ('dairy', 'Dairy'), ('grain', 'Grain'), ('other', 'Other')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('storage_type', models.CharField(choices=[('fridge', 'Fridge'), ('freezer', 'Freezer'), ('room_temp', 'Room Temperature')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Log Entry',
                'verbose_name_plural': 'Food Log Entries',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.TextField()),
                ('ingredients', models.JSONField()),
                ('serving', models.IntegerField(blank=True, null=True)),
                ('waste', models.JSONField(blank=True, default=list)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('has_leftovers', models.BooleanField(default=False)),
                ('leftovers_saved', models.BooleanField(default=False)),
                ('leftovers', models.JSONField(blank=True, null=True)),
                ('cuisine', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('mealTime', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('brunch', 'Brunch')], max_length=20)),
                ('consumed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
                'ordering': ['-consumed_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_logs', to='food.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waste Log',
                'verbose_name_plural': 'Waste Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
