# Generated by Django 5.2.9 on 2025-12-20 15:54

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('recipes', '0002_fix_ingredients_norm_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlogsys',
            name='is_consumed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='foodlogsys',
            name='name_normalized',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='foodlogsys',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='FoodComRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('n_ingredients', models.PositiveIntegerField(blank=True, null=True)),
                ('n_steps', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='foodcom', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'food.com Recipe',
                'verbose_name_plural': 'Food.com Recipes',
                'ordering': ['id'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['ingredients'], name='foodcom_ingredients_gin'), django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='foodcom_tags_gin')],
            },
        ),
        migrations.CreateModel(
            name='FoodLogUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('foodlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.foodlogsys')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.mealdbrecipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['user', 'used_at'], name='food_foodlo_user_id_a6cd09_idx'), models.Index(fields=['recipe'], name='food_foodlo_recipe__078a6d_idx'), models.Index(fields=['foodlog'], name='food_foodlo_foodlog_d801a2_idx')],
            },
        ),
    ]
