# Generated by Django 5.2.9 on 2025-12-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodlogsys_is_consumed_foodlogsys_name_normalized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='photo',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
