# Generated by Django 5.2.9 on 2026-01-04 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlogsys',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to='food.meal'),
        ),
        migrations.AddField(
            model_name='meal',
            name='steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mealTime',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('brunch', 'Brunch'), ('dessert', 'Dessert'), ('appetizer', 'Appetizer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wastelog',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_logs', to='food.meal'),
        ),
    ]
