# Generated by Django 6.0 on 2025-12-09 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_meal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-consumed_at'], 'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
        migrations.AddField(
            model_name='meal',
            name='consumed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='has_leftovers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='leftovers_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
