# Generated by Django 5.2.9 on 2026-01-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='source_mealdb_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
