# Generated by Django 5.2.9 on 2025-12-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodlogsys_is_consumed_foodlogsys_name_normalized_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodComRecipe',
        ),
    ]
