# Generated by Django 5.2.9 on 2025-12-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_meal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
