# Generated by Django 5.2.9 on 2025-12-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_delete_foodcomrecipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastelog',
            old_name='items',
            new_name='reuse_ideas',
        ),
        migrations.AddField(
            model_name='wastelog',
            name='disposal',
            field=models.CharField(default='compost', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastelog',
            name='estimated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastelog',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastelog',
            name='unit',
            field=models.CharField(default='unknow', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastelog',
            name='why',
            field=models.TextField(default='legacy data'),
            preserve_default=False,
        ),
    ]
