# Generated by Django 5.2.9 on 2025-12-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_foodlogsys_id_alter_meal_id'),
        ('food', '0004_alter_foodlogsys_id_alter_meal_id_alter_meal_waste_and_more'),
    ]

    operations = [
    ]
