# Generated by Django 5.2.9 on 2025-12-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='steps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
