# Generated by Django 5.2.9 on 2025-12-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_meal_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='mealTime',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('brunch', 'Brunch'), ('dessert', 'Dessert'), ('appetizer', 'Appetizer')], max_length=20),
        ),
    ]
