# Generated by Django 5.2.9 on 2025-12-16 22:04

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_merge_20251216_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodComRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.BigIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('n_ingredients', models.PositiveIntegerField(blank=True, null=True)),
                ('n_steps', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='foodcom', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'food.com Recipe',
                'verbose_name_plural': 'Food.com Recipes',
                'ordering': ['recipe_id'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['ingredients'], name='foodcom_ingredients_gin'), django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='foodcom_tags_gin')],
            },
        ),
    ]
