# Generated by Django 5.2.9 on 2025-12-16 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_foodcomrecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcomrecipe',
            options={'ordering': ['id'], 'verbose_name': 'food.com Recipe', 'verbose_name_plural': 'Food.com Recipes'},
        ),
        migrations.RemoveField(
            model_name='foodcomrecipe',
            name='recipe_id',
        ),
    ]
