# Generated by Django 5.2.9 on 2026-01-02 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_meal_source_mealdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlogsys',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to='food.meal'),
        ),
        migrations.AlterField(
            model_name='wastelog',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_logs', to='food.meal'),
        ),
    ]
