# Generated by Django 5.2.9 on 2026-01-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_foodlogsys_meal_alter_wastelog_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='has_leftovers',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='leftovers',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='leftovers_saved',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='waste',
        ),
    ]
