# Generated by Django 5.2.9 on 2025-12-18 19:50

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_foodcomrecipe_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mealdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealdb_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('cuisine', models.CharField(blank=True, default='', max_length=100)),
                ('instructions', models.TextField(blank=True, default='')),
                ('thumbnail', models.URLField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['ingredients'], name='recipe_ingredients_gin'), django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='recipe_tags_gin')],
            },
        ),
    ]
