# Generated by Django 5.2.9 on 2026-01-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_remove_meal_has_leftovers_remove_meal_leftovers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='has_leftovers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='leftovers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='leftovers_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='waste',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
