# Generated by Django 5.2.9 on 2026-01-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_meal_source_mealdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='steps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
