# Generated by Django 5.2.9 on 2026-01-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_foodlogsys_meal_meal_steps_alter_meal_mealtime_and_more'),
        ('food', '0010_alter_meal_photo_alter_meal_steps'),
    ]

    operations = [
    ]
