# Generated by Django 5.2.10 on 2026-01-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
