# Generated by Django 5.2.9 on 2025-12-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_id'),
        ('accounts', '0006_alter_user_id'),
    ]

    operations = [
    ]
