# Generated by Django 5.2.9 on 2025-12-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_0004_alter_user_id_0006_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='frist_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
