# Generated by Django 5.2.10 on 2026-01-11 16:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityParent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('community_type', models.CharField(choices=[('BLOG', 'Blog'), ('SHARING', 'Sharing'), ('MARKET', 'Market')], default='MARKET', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_parent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComMarket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured_image_key', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('pcs', 'Pieces'), ('portion', 'Portion')], max_length=10)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD_OUT', 'Sold Out'), ('EXPIRED', 'Expired'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_listings', to=settings.AUTH_USER_MODEL)),
                ('community_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_listings', to='community.communityparent')),
            ],
            options={
                'db_table': 'com_market',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_community_member', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_shares', models.IntegerField(default=0)),
                ('total_sales', models.IntegerField(default=0)),
                ('seller_status', models.CharField(choices=[('NONE', 'None'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='NONE', max_length=20)),
                ('subscription_plan', models.CharField(blank=True, choices=[('SELLER', 'Seller')], default=None, max_length=30, null=True)),
                ('banned_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('pcs', 'Pieces'), ('portion', 'Portion')], max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery')], default='COD', max_length=20)),
                ('buyer_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='community.commarket')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'market_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketOrderAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_line', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='community.marketorder')),
            ],
            options={
                'db_table': 'market_order_address',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('MARKET', 'Marketplace Listing'), ('USER', 'User'), ('BLOG', 'Blog Post'), ('SHARE', 'Shared Food')], max_length=20)),
                ('target_id', models.BigIntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISMISSED', 'Dismissed'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('admin_action', models.CharField(blank=True, choices=[('NONE', 'No Action'), ('SUSPEND_SELLER', 'Suspend Seller'), ('BAN_USER', 'Ban User'), ('DELETE_MARKET', 'Delete Market')], max_length=20, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(db_column='reporter_id', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='community_r_target__c00cf4_idx'), models.Index(fields=['status'], name='community_r_status_1d1979_idx')],
                'unique_together': {('reporter', 'target_type', 'target_id')},
            },
        ),
        migrations.CreateModel(
            name='MarketReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='community.commarket')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'market_review',
                'ordering': ['-created_at'],
                'unique_together': {('market', 'reviewer')},
            },
        ),
    ]
