# Generated by Django 5.2.9 on 2026-01-08 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityreport',
            name='admin_action',
            field=models.CharField(blank=True, choices=[('NONE', 'No Action'), ('SUSPEND_SELLER', 'Suspend Seller'), ('BAN_USER', 'Ban User'), ('DELETE_MARKET', 'Delete Market')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='communityreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='communityreport',
            unique_together={('reporter', 'target_type', 'target_id')},
        ),
        migrations.AddIndex(
            model_name='communityreport',
            index=models.Index(fields=['status'], name='community_r_status_1d1979_idx'),
        ),
    ]
