# Generated by Django 5.2.9 on 2026-01-07 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commarket',
            name='community_parent_id',
        ),
        migrations.RemoveField(
            model_name='commarket',
            name='seller_id',
        ),
        migrations.RemoveField(
            model_name='marketorder',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='marketorder',
            name='market_id',
        ),
        migrations.RemoveField(
            model_name='marketorder',
            name='seller_id',
        ),
        migrations.RemoveField(
            model_name='marketorderaddress',
            name='order_id',
        ),
        migrations.AddField(
            model_name='commarket',
            name='community_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_listings', to='community.communityparent'),
        ),
        migrations.AddField(
            model_name='commarket',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketorder',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketorder',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='community.commarket'),
        ),
        migrations.AddField(
            model_name='marketorder',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketorderaddress',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='community.marketorder'),
        ),
    ]
