# Generated by Django 5.2.9 on 2026-01-07 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_commarket_community_parent_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commarket',
            name='community_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_listings', to='community.communityparent'),
        ),
        migrations.AlterField(
            model_name='commarket',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='community.commarket'),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketorderaddress',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='community.marketorder'),
        ),
    ]
