# Generated by Django 5.2.10 on 2026-01-11 16:33

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDBRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealdb_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('cuisine', models.CharField(blank=True, default='', max_length=100)),
                ('instructions', models.TextField(blank=True, default='')),
                ('thumbnail', models.URLField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('youtube', models.URLField(blank=True, default='')),
                ('source', models.URLField(blank=True, default='')),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('ingredient_tokens', models.JSONField(blank=True, default=list, null=True)),
                ('meal_time', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('brunch', 'Brunch')], db_index=True, max_length=20, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['ingredient_tokens'], name='mealdb_ing_tokens_gin'), django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='mealdb_tags_gin'), models.Index(fields=['cuisine'], name='recipes_mea_cuisine_af4f25_idx'), models.Index(fields=['category'], name='recipes_mea_categor_80e79d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecipeFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='recipes.mealdbrecipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'recipe'), name='uniq_favorite_user_recipe')],
            },
        ),
        migrations.CreateModel(
            name='RecipeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='recipes.mealdbrecipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'recipe'), name='uniq_review_user_recipe')],
            },
        ),
    ]
