# Generated by Django 5.2.9 on 2025-12-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_fix_ingredients_norm_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealdbrecipe',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
