# Generated by Django 5.2.9 on 2026-01-06 17:39

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_fix_ingredients_norm_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mealdbrecipe',
            name='mealdb_ing_norm_gin',
        ),
        migrations.RemoveField(
            model_name='mealdbrecipe',
            name='ingredients_norm',
        ),
        migrations.AddField(
            model_name='mealdbrecipe',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealdbrecipe',
            name='ingredient_tokens',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddIndex(
            model_name='mealdbrecipe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['ingredient_tokens'], name='mealdb_ing_tokens_gin'),
        ),
    ]
