# Generated by Django 5.2.9 on 2025-12-30 19:51

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_mealdbrecipe_embedding'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mealdbrecipe',
            name='mealdb_ing_norm_gin',
        ),
        migrations.RemoveField(
            model_name='mealdbrecipe',
            name='ingredients_norm',
        ),
        migrations.AddField(
            model_name='mealdbrecipe',
            name='ingredient_tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddIndex(
            model_name='mealdbrecipe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['ingredient_tokens'], name='mealdb_ing_tokens_gin'),
        ),
    ]
