# Generated by Django 5.2.9 on 2025-12-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_mealdbrecipe_mealdb_ing_norm_gin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdbrecipe',
            name='ingredient_tokens',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
