# Generated by Django 5.2.10 on 2026-01-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_mealdbrecipe_ingredient_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdbrecipe',
            name='ingredient_tokens',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
