# Generated by Django 5.2.9 on 2026-01-02 22:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('days', models.PositiveIntegerField(default=3)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_plan', to='meal_plans.mealplan')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('brunch', 'Brunch'), ('dessert', 'Dessert'), ('appetizer', 'Appetizer')], max_length=20)),
                ('is_skipped', models.BooleanField(default=False)),
                ('is_replaced', models.BooleanField(default=False)),
                ('replaced_at', models.DateTimeField(blank=True, null=True)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.meal')),
                ('meal_plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='meal_plans.mealplanday')),
                ('original_meal', models.ForeignKey(blank=True, help_text='Original meal before replacement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_from', to='food.meal')),
            ],
            options={
                'verbose_name': 'Meal Plan Meal',
                'verbose_name_plural': 'Meal Plan Meals',
                'ordering': ['meal_plan_day__date', 'meal_time'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanFoodUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('food_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_usages', to='food.foodlogsys')),
                ('meal_plan_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_usages', to='meal_plans.mealplanmeal')),
            ],
            options={
                'verbose_name': 'Meal Plan Food Usage',
                'verbose_name_plural': 'Meal Plan Food Usages',
            },
        ),
        migrations.AddIndex(
            model_name='mealplanday',
            index=models.Index(fields=['date', 'is_confirmed'], name='meal_plans__date_869862_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mealplanday',
            unique_together={('meal_plan', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='mealplanmeal',
            unique_together={('meal_plan_day', 'meal_time')},
        ),
    ]
