# Generated by Django 5.2.9 on 2026-01-04 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_merge_20260104_1819'),
        ('meal_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplanmeal',
            name='draft_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='draft_cuisine',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='draft_ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='draft_photo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='draft_serving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='draft_source_mealdb_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='draft_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='draft_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mealplanmeal',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_plan_meals', to='food.meal'),
        ),
    ]
