# Generated by Django 5.2.9 on 2025-12-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealplanfoodusage',
            options={'verbose_name': 'Meal Plan Food Usage', 'verbose_name_plural': 'Meal Plan Food Usages'},
        ),
    ]
