# Generated by Django 5.2.9 on 2025-12-31 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('meal_plans', '0002_alter_mealplanmeal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplanmeal',
            name='is_replaced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='original_meal',
            field=models.ForeignKey(blank=True, help_text='Original meal before replacement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_from', to='food.meal'),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealplanmeal',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.meal'),
        ),
    ]
