# Generated by Django 6.0 on 2025-12-09 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLogSys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('bread', 'Bread'), ('meat', 'Meat'), ('dairy', 'Dairy'), ('grain', 'Grain'), ('other', 'Other')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('storage_type', models.CharField(choices=[('fridge', 'Fridge'), ('freezer', 'Freezer'), ('room_temp', 'Room Temperature')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Log Entry',
                'verbose_name_plural': 'Food Log Entries',
                'ordering': ['expiry_date'],
            },
        ),
    ]
