# Generated by Django 6.0 on 2025-12-09 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.TextField()),
                ('ingredients', models.JSONField()),
                ('serving', models.IntegerField(blank=True, null=True)),
                ('waste', models.TextField(blank=True, null=True)),
                ('calories', models.IntegerField()),
                ('leftovers', models.JSONField(blank=True, null=True)),
                ('cuisine', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('mealTime', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('brunch', 'Brunch')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
